# Ref: http://docs.ros.org/en/noetic/api/robot_localization/html/state_estimation_nodes.html

ekf_filter_node:
    ros__parameters:

        frequency: 25.0
        sensor_timeout: 0.1
        two_d_mode: true

        transform_time_offset: 0.0
        transform_timeout: 0.1

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        publish_tf: true
        publish_acceleration: false

        odom0: /rosbot_base_controller/odom
        odom0_config: [false, false, false,
                    false, false, false,
                    true, true, false,
                    false, false, true,
                    false, false, false]
        odom0_queue_size: 2
        odom0_nodelay: false
        odom0_differential: false
        odom0_relative: true

        imu0: /imu_broadcaster/imu
        imu0_config: [false, false, false,
                    false, false, false,
                    false, false, false,
                    false, false, true,
                    true, true, false]
        imu0_queue_size: 5
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        imu0_remove_gravitational_acceleration: true

        reset_on_time_jump: false
        predict_to_current_time: false
        print_diagnostics: false

        # Selected values ​​experimentally so as to ensure relatively fast convergence (values ​​should be about 10x higher than the sensor variance values)
        dynamic_process_noise_covariance: true
        process_noise_covariance: [5e-3,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   5e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   5e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   1e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   1e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   1e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   3e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   3e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   3e-3,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-2,  0.0,   0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-2,  0.0,   0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-2,  0.0,   0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-5,  0.0,   0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-5,  0.0,
                                    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-5]
