bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_xml_filename: "bt_navigator.xml"

dwb_controller:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    debug_trajectory_details: False
    min_vel_x: 0.0
    min_vel_y: 0.0
    max_vel_x: 0.26
    max_vel_y: 0.0
    min_vel_theta: 0.1
    max_vel_theta: 1.0
    min_speed_xy: 0.0
    max_speed_xy: 0.26
    min_speed_theta: 0.0
    min_x_velocity_threshold: 0.001
    # Add high threshold velocity for turtlebot 3 issue.
    # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
    min_y_velocity_threshold: 1.0
    min_theta_velocity_threshold: 0.001
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    decel_lim_theta: -3.2
    vx_samples: 20
    vy_samples: 5
    vtheta_samples: 20
    sim_time: 2.5
    linear_granularity: 0.05
    xy_goal_tolerance: 0.25
    yaw_goal_tolerance: 0.75
    transform_tolerance: 1.0
    critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
    BaseObstacle.scale: 0.02
    PathAlign.scale: 0.0
    GoalAlign.scale: 0.0
    PathDist.scale: 32.0
    GoalDist.scale: 24.0
    RotateToGoal.scale: 32.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      global_frame: odom
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.025
      footprint: '[[0.14, 0.16], [0.14, -0.16], [-0.14, -0.16], [-0.14, 0.16]]'
      inflation_layer.cost_scaling_factor: 3.0
      obstacle_layer:
        enabled: True
      static_layer:
        enabled: true
        subscribe_to_updates: true
        map_subscribe_transient_local: true
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      footprint: '[[0.14, 0.16], [0.14, -0.16], [-0.14, -0.16], [-0.14, 0.16]]'
      obstacle_layer:
        enabled: True
      static_layer:
        enabled: true
        subscribe_to_updates: true
        map_subscribe_transient_local: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

lifecycle_manager:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names: ['world_model', 'dwb_controller',
                 'navfn_planner', 'bt_navigator']

lifecycle_manager_service_client:
  ros__parameters:
    use_sim_time: False

lifecycle_manager_client_service_client:
  ros__parameters:
    use_sim_time: False

navfn_planner:
  ros__parameters:
    use_sim_time: False
    tolerance: 0.0
    use_astar: false

navfn_planner_GetCostmap_client:
  ros__parameters:
    use_sim_time: False

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

world_model:
  ros__parameters:
    use_sim_time: False
